const { Cars } = require('../models');

const carsData = [
  {
    car_name: 'Huracan',
    makes_name: 'Lamborghini',
    price: 349.99,
    stock: 3,
    makes_id: 1,
  },
  {
    car_name: 'Urus',
    makes_name: 'Lamborghini',
    price: 14.99,
    stock: 2,
    makes_id: 1,
  },
  {
    car_name: 'Revuelto',
    makes_name: 'Lamborghini',
    price: 14.99,
    stock: 3,
    makes_id: 1,
  },
  {
    car_name: 'Gallardo',
    makes_name: 'Lamborghini',
    price: 14.99,
    stock: 3,
    makes_id: 1,
  },
  {
    car_name: 'Murcielago',
    makes_name: 'Lamborghini',
    price: 14.99,
    stock: 3,
    makes_id: 1,
  },
  {
    car_name: 'SF90',
    makes_name: 'Ferrari',
    price: 14.99,
    stock: 3,
    makes_id: 2,
  },
  {
    car_name: '296GTB',
    makes_name: 'Ferrari',
    price: 14.99,
    stock: 3,
    makes_id: 2,
  },
  {
    car_name: '12Cilindri',
    makes_name: 'Ferrari',
    price: 14.99,
    stock: 3,
    makes_id: 3,
  },
  {
    car_name: 'Purosangue',
    makes_name: 'Ferrari',
    price: 14.99,
    stock: 3,
    makes_id: 3,
  },
  {
    car_name: 'Roma',
    makes_name: 'Ferrari',
    price: 14.99,
    stock: 3,
    makes_id: 3,
  },
  {
    car_name: 'Bentayga',
    makes_name: 'Bentley',
    price: 14.99,
    stock: 3,
    makes_id: 4,
  },
  {
    car_name: 'Continental',
    makes_name: 'Bentley',
    price: 14.99,
    stock: 3,
    makes_id: 4,
  },
  {
    car_name: 'Flying Spur',
    makes_name: 'Bentley',
    price: 14.99,
    stock: 3,
    makes_id: 4,
  },
  {
    car_name: 'Continental GT Convertible',
    makes_name: 'Bentley',
    price: 14.99,
    stock: 3,
    makes_id: 4,
  },
  {
    car_name: 'Continental GT Coupe',
    makes_name: 'Bentley',
    price: 14.99,
    stock: 3,
    makes_id: 4,
  }, 
  {
    car_name: 'Phantom',
    makes_name: 'Rolls-Royce',
    price: 14.99,
    stock: 3,
    makes_id: 5,
  },
  {
    car_name: 'Cullinan',
    makes_name: 'Rolls-Royce',
    price: 14.99,
    stock: 3,
    makes_id: 5,
  },
  {
    car_name: 'Ghost',
    makes_name: 'Rolls-Royce',
    price: 14.99,
    stock: 3,
    makes_id: 5,
  },
  {
    car_name: 'Spectre',
    makes_name: 'Rolls-Royce',
    price: 14.99,
    stock: 3,
    makes_id: 5,
  },
  {
    car_name: 'Ghost Black Badge',
    makes_name: 'Rolls-Royce',
    price: 1599.99,
    stock: 3,
    makes_id: 5,
  },
  {
    car_name: 'F-Pace',
    makes_name: 'Jaguar',
    price: 1399.99,
    stock: 3,
    makes_id: 6,
  },
  {
    car_name: 'E-Pace',
    makes_name: 'Jaguar',
    price: 1299.99,
    stock: 3,
    makes_id: 6,
  },
  {
    car_name: 'F-Type',
    makes_name: 'Jaguar',
    price: 1399.99,
    stock: 3,
    makes_id: 6,
  },
  {
    car_name: 'XF',
    makes_name: 'Jaguar',
    price: 1499.99,
    stock: 3,
    makes_id: 6,
  },
  {
    car_name: 'F-Type Convertible',
    makes_name: 'Jaguar',
    price: 1399.99,
    stock: 3,
    makes_id: 6,
  },
  {
    car_name: 'Vantage',
    makes_name: 'Aston Martin',
    price: 1599.99,
    stock: 3,
    makes_id: 7,
  },
  {
    car_name: 'DBX',
    makes_name: 'Aston Martin',
    price: 1599.99,
    stock: 3,
    makes_id: 7,
  },
  {
    car_name: 'DB12',
    makes_name: 'Aston Martin',
    price: 1599.99,
    stock: 3,
    makes_id: 7,
  },
  {
    car_name: 'DBS',
    makes_name: 'Aston Martin',
    price: 1599.99,
    stock: 3,
    makes_id: 7,
  },
  {
    car_name: 'Valour',
    makes_name: 'Aston Martin',
    price: 1599.99,
    stock: 3,
    makes_id: 7,
  },
  {
    car_name: 'Vantage',
    makes_name: 'Mercedes-Benz',
    price: 1599.99,
    stock: 3,
    makes_id: 8,
  },
  {
    
  }
  

 
];

const seedCars = () => Cars.bulkCreate(carsData);

module.exports = seedCars;
