const { Cars } = require('../models');

const carsData = [
  {
    car_name: 'Huracan',
    makes_name: 'Lamborghini',
    price: 349.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/lamborghiniHuracan.jpg",
  },
  {
    car_name: 'Urus',
    makes_name: 'Lamborghini',
    price: 14.99,
    color: 'green',
    stock: 2,
    image_url: "./fleetImages/lamborghiniUrus.jpg",
  },
  {
    car_name: 'Revuelto',
    makes_name: 'Lamborghini',
    price: 14.99,
    color: 'gold',
    stock: 3,
    image_url: "./fleetImages/lamborghiniRevuelto.jpg",
  },
  {
    car_name: 'Gallardo',
    makes_name: 'Lamborghini',
    price: 14.99,
    color: 'green',
    stock: 3,
    image_url: "./fleetImages/lamborghiniGallardo.jpg",
  },
  {
    car_name: 'Murcielago',
    makes_name: 'Lamborghini',
    price: 14.99,
    color: 'yellow',
    stock: 3,
    image_url: "./fleetImages/lamborghiniMurcielago.jpg",
  },
  {
    car_name: 'SF90',
    makes_name: 'Ferrari',
    price: 14.99,
    color: 'red',
    stock: 3,
    image_url: "./fleetImages/ferrariSF90.jpg",
  },
  {
    car_name: '296GTB',
    makes_name: 'Ferrari',
    price: 14.99,
    color: 'red',
    stock: 3,
    image_url: "./fleetImages/ferrari296GTB.jpg",
  },
  {
    car_name: '12Cilindri',
    makes_name: 'Ferrari',
    price: 14.99,
    color: 'red',
    stock: 3,
    image_url: "./fleetImages/ferrari12Cilindri.jpg",
  },
  {
    car_name: 'Purosangue',
    makes_name: 'Ferrari',
    price: 14.99,
    color: 'red',
    stock: 3,
    image_url: "./fleetImages/ferrariPurosangue.jpg",
  },
  {
    car_name: 'Roma',
    makes_name: 'Ferrari',
    price: 14.99,
    color: 'red',
    stock: 3,
    image_url: "./fleetImages/ferrariRoma.jpg",
  },
  {
    car_name: 'Bentayga',
    makes_name: 'Bentley',
    price: 14.99,
    color: 'silver',
    stock: 3,
    image_url: "./fleetImages/bentleyBentayga.jpg",
  },
  {
    car_name: 'Continental',
    makes_name: 'Bentley',
    price: 14.99,
    color: 'gun metal',
    stock: 3,
    image_url: "./fleetImages/bentleyContinental.jpg",
  },
  {
    car_name: 'Flying Spur',
    makes_name: 'Bentley',
    price: 14.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/bentleyFlyingSpur.jpg",
  },
  {
    car_name: 'Continental GT Convertible',
    makes_name: 'Bentley',
    price: 14.99,
    color: 'white',
    stock: 3,
    image_url: "./fleetImages/bentleyContinentalGT.jpg",
  },
  {
    car_name: 'Continental GT Coupe',
    makes_name: 'Bentley',
    price: 14.99,
    color: 'blue',
    stock: 3,
    image_url: "./fleetImages/bentleyGTcoupe.jpg",
  },
  {
    car_name: 'Phantom',
    makes_name: 'Rolls-Royce',
    price: 14.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/roycePhantom.jpg",
  },
  {
    car_name: 'Cullinan',
    makes_name: 'Rolls-Royce',
    price: 14.99,
    color: 'silver',
    stock: 3,
    image_url: "./fleetImages/royceCullinan.jpg",
  },
  {
    car_name: 'Ghost',
    makes_name: 'Rolls-Royce',
    price: 14.99,
    color: 'gray',
    stock: 3,
    image_url: "./fleetImages/royceGhost.jpg",
  },
  {
    car_name: 'Spectre',
    makes_name: 'Rolls-Royce',
    price: 14.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/royceSpectre.jpg",
  },
  {
    car_name: 'Ghost Black Badge',
    makes_name: 'Rolls-Royce',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/royceBlackBadge.jpg",
  },
  {
    car_name: 'F-Pace',
    makes_name: 'Jaguar',
    price: 1399.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/jaguarFPace.jpg",
  },
  {
    car_name: 'E-Pace',
    makes_name: 'Jaguar',
    price: 1299.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/jaguarEPace.jpg",
  },
  {
    car_name: 'F-Type',
    makes_name: 'Jaguar',
    price: 1399.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/jaguarFType.jpg",
  },
  {
    car_name: 'XF',
    makes_name: 'Jaguar',
    price: 1499.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/jaguarXF.jpg",
  },
  {
    car_name: 'F-Type Convertible',
    makes_name: 'Jaguar',
    price: 1399.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/jaguarFTypeConvertible.jpg",
  },
  {
    car_name: 'Vantage',
    makes_name: 'Aston Martin',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/amVantage.jpg",
  },
  {
    car_name: 'DBX',
    makes_name: 'Aston Martin',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/amDBX.jpg",
  },
  {
    car_name: 'DB12',
    makes_name: 'Aston Martin',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/amDB12.jpg",
  },
  {
    car_name: 'DBS',
    makes_name: 'Aston Martin',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/amDBS.jpg",
  },
  {
    car_name: 'Valour',
    makes_name: 'Aston Martin',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/amValour.jpg",
  },
  {
    car_name: 'G-Class',
    makes_name: 'Mercedes-Benz',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/mercedesGClass.jpg",
  },
  {
    car_name: 'GLS',
    makes_name: 'Mercedes-Benz',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/mercedesMaybach.jpg",
  },
  {
    car_name: 'Maybach',
    makes_name: 'Mercedes-Benz',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/mercedesSClass.jpg",
  },
  {
    car_name: 'S Class',
    makes_name: 'Mercedes-Benz',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/mercedesAMGGT.jpg",
  },
  {
    car_name: 'AMG GT',
    makes_name: 'Mercedes-Benz',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/mercedesAMGGT.jpg",
  },
  {
    car_name: 'X7',
    makes_name: 'BMW',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/bmwX7.jpg",
  },
  {
    car_name: '750i',
    makes_name: 'BMW',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/bmw750i.jpg",
  },
  {
    car_name: 'M3',
    makes_name: 'BMW',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/bmwM3.jpg",
  },
  {
    car_name: 'i8',
    makes_name: 'BMW',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/bmwi8.jpg",
  },
  {
    car_name: 'M5',
    makes_name: 'BMW',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/bmwM5.jpg",
  },
  {
    car_name: 'Z4',
    makes_name: 'BMW',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/bmwZ4.jpg",
  },
  {
    car_name: 'Ghibli',
    makes_name: 'Maserati',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/maseratiGhibli.jpg",
  },
  {
    car_name: 'Gran Turismo',
    makes_name: 'Maserati',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/maseratiGranTurismo.jpg",
  },
  {
    car_name: 'Levante',
    makes_name: 'Maserati',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/maseratiLevante.jpg",
  },
  {
    car_name: 'MC20',
    makes_name: 'Maserati',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/maseratiMC20.jpg",
  },
  {
    car_name: 'Model S',
    makes_name: 'Tesla',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/teslaModelS.jpg",
  },
  {
    car_name: 'Model X',
    makes_name: 'Tesla',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/teslaModelX.jpg",
  },
  {
    car_name: 'Cybertruck',
    makes_name: 'Tesla',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/teslaCybertruck.jpg",
  },
  {
    car_name: 'Model Y',
    makes_name: 'Tesla',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/teslaModelY.jpg",
  },
  {
    car_name: 'Roadster',
    makes_name: 'Tesla',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/teslaRoadster.jpg",
  },
  {
    car_name: 'GT3 RS',
    makes_name: 'Porsche',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/porscheGT3RS.jpg",
  },
  {
    car_name: 'Panamera',
    makes_name: 'Porsche',
    price: 1599.99,
    color: 'gray',
    stock: 3,
    image_url: "./fleetImages/porschePanamera.jpg",
  },
  {
    car_name: 'Cayman',
    makes_name: 'Porsche',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/porscheCayman.jpg",
  },
  {
    car_name: 'Cayenne',
    makes_name: 'Porsche',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/porscheCayenne.jpg",
  },
  {
    car_name: 'Macan',
    makes_name: 'Porsche',
    price: 1599.99,
    color: 'green',
    stock: 3,
    image_url: "./fleetImages/porscheMacan.jpg",
  },
  {
    car_name: 'Q7',
    makes_name: 'Audi',
    price: 1599.99,
    color: 'white',
    stock: 3,
    image_url: "./fleetImages/audiQ7.jpg",
  },
  {
    car_name: 'A8',
    makes_name: 'Audi',
    price: 1599.99,
    color: 'black',
    stock: 3,
    image_url: "./fleetImages/audiA8.jpg",
  },
  {
    car_name: 'R8',
    makes_name: 'Audi',
    price: 1599.99,
    color: 'orange',
    stock: 3,
    image_url: "./fleetImages/audiR8.jpg",
  },
  {
    car_name: 'RS6',
    makes_name: 'Audi',
    price: 1599.99,
    color: 'yellow',
    stock: 3,
    image_url: "./fleetImages/audiRS6.jpg",
  },
  {
    car_name: 'RS4',
    makes_name: 'Audi',
    price: 1599.99,
    color: 'blue',
    stock: 3,
    image_url: "./fleetImages/audiRS4.jpg",
  },
];


const seedCars = () => Cars.bulkCreate(carsData);

module.exports = seedCars;
